/*!
This package provides simple & fast programmatic access to the icons from
[vscode-icons](https://github.com/vscode-icons/vscode-icons).

This crate is heavily optimized for small file size.

## Usage


 */

#![no_std]
#![cfg_attr(target_arch = "wasm32", feature(core_intrinsics))]

use core::{slice, str};
use fst::Map;
use lazy_static::lazy_static;

lazy_static! {
    static ref FILENAME_ICONS: Map<&'static [u8]> = {
        const FILENAME_ICONS_BYTES: &[u8] =
            include_bytes!(concat!(env!("OUT_DIR"), "/filename_icons.bin"));

        // the bytes are generated by fst in the build script, so we can use `unwrap_unchecked`
        unsafe { Map::new(FILENAME_ICONS_BYTES).unwrap_unchecked() }
    };
    static ref EXT_ICONS: Map<&'static [u8]> = {
        const EXT_ICONS_BYTES: &[u8] = include_bytes!(concat!(env!("OUT_DIR"), "/ext_icons.bin"));

        // the bytes are generated by fst in the build script, so we can use `unwrap_unchecked`
        unsafe {
            Map::new(EXT_ICONS_BYTES).unwrap_unchecked()
        }
    };
    static ref FOLDER_ICONS: Map<&'static [u8]> = {
        const FOLDER_ICONS_BYTES: &[u8] =
            include_bytes!(concat!(env!("OUT_DIR"), "/folder_icons.bin"));

        // the bytes are generated by fst in the build script, so we can use `unwrap_unchecked`
        unsafe{ Map::new(FOLDER_ICONS_BYTES).unwrap_unchecked() }
    };
}

#[no_mangle]
#[inline]
unsafe fn _get_icon_for_file(data: *mut u8, len: usize) -> Option<u64> {
    let buf = unsafe { slice::from_raw_parts(data, len) };
    let path = str::from_utf8_unchecked(buf);

    let icon = FILENAME_ICONS.get(path.as_bytes()).or_else(|| {
        let ext = path.rsplit_once('.')?.1;

        EXT_ICONS.get(ext.as_bytes())
    });

    icon
}

#[no_mangle]
#[inline]
unsafe fn _get_icon_for_folder(data: *mut u8, len: usize) -> Option<u64> {
    let buf = unsafe { slice::from_raw_parts(data, len) };
    let path = str::from_utf8_unchecked(buf);

    let icon = FOLDER_ICONS.get(path.as_bytes());

    icon
}

/// Returns the ID of an icon for a given file.
///
/// If no icon can be found, `None` is returned.
/// The ID corresponds to the file names in the `icons` folder
#[cfg(not(target_arch = "wasm32"))]
pub fn get_icon_for_file(path: &str) -> Option<u64> {
    unsafe { _get_icon_for_file(path.as_bytes().as_ptr() as *mut u8, path.len()) }
}

/// Returns the ID of an icon for a given folder.
///
/// If no icon can be found, `None` is returned.
/// The ID corresponds to the file names in the `icons` folder
#[cfg(not(target_arch = "wasm32"))]
pub fn get_icon_for_folder(path: &str) -> Option<u64> {
    unsafe { _get_icon_for_folder(path.as_bytes().as_ptr() as *mut u8, path.len()) }
}

#[cfg(target_arch = "wasm32")]
#[panic_handler]
fn panic_handler(_info: &core::panic::PanicInfo) -> ! {
    core::intrinsics::abort()
}
